#¶Ë¿Ú
server:
  port: 1234
es:
  config:
    cluster-name: elasticsearch
    cluster-nodes: http://localhost:9200
    username: elastic
    password: elastic
    connect-timeout: 5000
    socket-timeout: 30000
    connection-request-timeout: 30000
  indices: test